version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: support-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: support-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/support_ticketing
      - JWT_SECRET=your_secret_key
      - ML_SERVICE_URL=http://ml:8000
    depends_on:
      - mongo
      - ml

  ml:
    build: ./ml
    container_name: support-ml
    ports:
      - "8000:8000"

  frontend:
    build: ./client
    container_name: support-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mongo_data:
